# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'caesar.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

import os
os.environ['QT_QPA_PLATFORM_PLUGIN_PATH'] = "../platforms"


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(476, 450)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(130, 15, 220, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_identity = QtWidgets.QLabel(self.centralwidget)
        self.label_identity.setGeometry(QtCore.QRect(80, 50, 321, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.label_identity.setFont(font)
        self.label_identity.setAlignment(QtCore.Qt.AlignCenter)
        self.label_identity.setObjectName("label_identity")
        self.txt_plain_text = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txt_plain_text.setGeometry(QtCore.QRect(80, 90, 381, 91))
        self.txt_plain_text.setObjectName("txt_plain_text")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 90, 51, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 210, 47, 13))
        self.label_3.setObjectName("label_3")
        self.txt_key = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_key.setGeometry(QtCore.QRect(80, 200, 381, 31))
        self.txt_key.setObjectName("txt_key")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 270, 51, 16))
        self.label_4.setObjectName("label_4")
        self.txt_cipher_text = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txt_cipher_text.setGeometry(QtCore.QRect(80, 270, 381, 91))
        self.txt_cipher_text.setObjectName("txt_cipher_text")
        self.btn_encrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btn_encrypt.setGeometry(QtCore.QRect(80, 380, 100, 30))
        self.btn_encrypt.setObjectName("btn_encrypt")
        self.btn_decrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btn_decrypt.setGeometry(QtCore.QRect(360, 380, 100, 30))
        self.btn_decrypt.setObjectName("btn_decrypt")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 476, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Caesar Cipher - Trần Nam Định"))
        self.label.setText(_translate("MainWindow", "CAESAR CIPHER"))
        self.label_identity.setText(_translate("MainWindow", "Trần Nam Định _ 2380600508"))
        self.label_2.setText(_translate("MainWindow", "Plaintext"))
        self.label_3.setText(_translate("MainWindow", "Key"))
        self.label_4.setText(_translate("MainWindow", "Ciphertext"))
        self.btn_encrypt.setText(_translate("MainWindow", "Encrypt"))
        self.btn_decrypt.setText(_translate("MainWindow", "Decrypt"))


# === THÊM LOGIC XỬ LÝ SỰ KIỆN KẾT NỐI API FLASK ===
import requests
from PyQt5.QtWidgets import QMessageBox

def handle_encrypt(ui):
    text = ui.txt_plain_text.toPlainText().strip()
    key = ui.txt_key.toPlainText().strip()
    if not text or not key:
        QMessageBox.warning(None, 'Thông báo', 'Vui lòng nhập Plaintext và Key!')
        return
    try:
        res = requests.post('http://127.0.0.1:5050/caesar/encrypt', data={'inputPlainText': text, 'inputKeyPlain': key})
        if res.status_code == 200:
            raw = res.text
            clean = raw.split("encrypted text: ")[1].strip() if "encrypted text:" in raw else raw
            ui.txt_cipher_text.setPlainText(clean)
    except Exception as e:
        QMessageBox.critical(None, 'Lỗi kết nối', 'Hãy chắc chắn bạn đã bật Server Flask Lab 02 ở cổng 5050!')

def handle_decrypt(ui):
    text = ui.txt_cipher_text.toPlainText().strip()
    key = ui.txt_key.toPlainText().strip()
    if not text or not key:
        QMessageBox.warning(None, 'Thông báo', 'Vui lòng nhập Ciphertext và Key!')
        return
    try:
        res = requests.post('http://127.0.0.1:5050/caesar/decrypt', data={'inputCipherText': text, 'inputKeyCipher': key})
        if res.status_code == 200:
            raw = res.text
            clean = raw.split("decrypted text: ")[1].strip() if "decrypted text:" in raw else raw
            ui.txt_plain_text.setPlainText(clean)
    except Exception as e:
        QMessageBox.critical(None, 'Lỗi kết nối', 'Hãy chắc chắn bạn đã bật Server Flask Lab 02 ở cổng 5050!')


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    
    # Kết nối logic xử lý vào nút bấm giao diện
    ui.btn_encrypt.clicked.connect(lambda: handle_encrypt(ui))
    ui.btn_decrypt.clicked.connect(lambda: handle_decrypt(ui))
    
    MainWindow.show()
    sys.exit(app.exec_())